In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import torch
import torch.nn as nn

In [3]:
class SimpleNN(nn.Module):

    def __init__(self):
        super(SimpleNN, self).__init__()

        self.l1 = nn.Linear(100, 200)
        self.relu1 = nn.ReLU()
        self.l2 = nn.Linear(200, 10)
        self.softmax = nn.Softmax()

    def forward(self, x):
        out = self.l1(x)
        out = self.relu1(out)
        out = self.l2(out)
        logit = self.softmax(out)
        return logit    


In [4]:

model = SimpleNN()

print("SImple Model:")
print(model)

SImple Model:
SimpleNN(
  (l1): Linear(in_features=100, out_features=200, bias=True)
  (relu1): ReLU()
  (l2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


In [5]:
print("\n\nOne layer:")
print(model.l2)



One layer:
Linear(in_features=200, out_features=10, bias=True)


In [6]:
print("\n\nModel Parameters:")
for param in model.parameters():
    print(param)




Model Parameters:
Parameter containing:
tensor([[ 0.0927, -0.0118,  0.0569,  ...,  0.0489,  0.0685,  0.0830],
        [ 0.0336, -0.0328,  0.0860,  ...,  0.0539, -0.0408, -0.0146],
        [ 0.0792,  0.0938, -0.0004,  ..., -0.0920,  0.0851,  0.0132],
        ...,
        [-0.0632, -0.0337,  0.0988,  ..., -0.0249,  0.0073,  0.0930],
        [-0.0403, -0.0017, -0.0854,  ..., -0.0592, -0.0729, -0.0615],
        [-0.0949,  0.0770, -0.0501,  ...,  0.0973,  0.0944, -0.0858]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0901, -0.0517,  0.0531, -0.0659,  0.0273, -0.0804, -0.0410,  0.0189,
        -0.0791,  0.0415,  0.0598,  0.0074, -0.0013, -0.0679, -0.0065, -0.0146,
        -0.0159,  0.0878,  0.0668, -0.0531, -0.0127, -0.0814, -0.0820,  0.0405,
         0.0444, -0.0744,  0.0200, -0.0512, -0.0912,  0.0095, -0.0600, -0.0910,
        -0.0259,  0.0402, -0.0310,  0.0716,  0.0730,  0.0753, -0.0238,  0.0434,
         0.0039,  0.0834,  0.0745, -0.0808,  0.0372,  0.0826,  0.0089,  0.0

In [10]:
for param in model.l2.parameters():
    print(param)

Parameter containing:
tensor([[-6.6060e-03, -6.8508e-02, -3.2391e-02,  ...,  3.6988e-02,
         -2.8810e-02, -2.3560e-02],
        [-6.2117e-02,  3.1846e-02,  2.2373e-02,  ...,  3.3649e-02,
         -6.8640e-02, -2.2484e-02],
        [ 5.9123e-02, -3.6528e-02, -6.5661e-02,  ..., -1.3733e-02,
          2.4830e-02, -5.4032e-02],
        ...,
        [ 6.4745e-02,  1.2834e-02, -8.4134e-05,  ..., -4.9906e-03,
         -2.6193e-02, -2.6837e-02],
        [ 1.9265e-03,  1.7134e-02,  6.7478e-03,  ...,  6.3292e-02,
         -1.2229e-02,  6.1269e-02],
        [-1.0429e-02,  2.3475e-02,  2.8634e-02,  ..., -1.4289e-02,
         -3.1425e-02, -5.5643e-02]], requires_grad=True)
Parameter containing:
tensor([-0.0654,  0.0315,  0.0016,  0.0379, -0.0038, -0.0554,  0.0262, -0.0429,
         0.0504, -0.0233], requires_grad=True)


In [11]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\nOutput:')
print(y)

Input:
tensor([[0.6995, 0.4650, 0.7213]])


Weight and Bias parameters:
Parameter containing:
tensor([[0.0210, 0.5462, 0.4205],
        [0.5173, 0.1578, 0.3339]], requires_grad=True)
Parameter containing:
tensor([-0.4607, -0.2833], requires_grad=True)


Output:
tensor([[0.1112, 0.3928]], grad_fn=<AddmmBackward0>)
