# Tensor with Pytorch.

Create  a tensor

In [ ]:
import torch

In [20]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [21]:
x.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [22]:
z = x.view(1,9)
z, z.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Stacked

In [23]:
x_stacked_vertically = torch.stack([x,x,x,x], dim=0)
x_stacked_vertically

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [24]:
x_stacked_horz = torch.stack([x,x,x,x], dim=1)
x_stacked_horz

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [25]:
x_sqeez = x.squeeze()
x_sqeez

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
 x = torch.zeros(2,1,2,1,2)
 x.size()

torch.Size([2, 1, 2, 1, 2])

In [32]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [31]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [33]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [34]:
# Permute
x = torch.randn(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [35]:
x

tensor([[[-1.7724, -0.7654, -1.5663,  0.9340,  1.6030],
         [-0.9666,  0.3055, -1.5214,  0.8957, -0.1274],
         [ 1.1967,  0.6901, -1.1785,  1.8581,  1.3833]],

        [[ 0.1115,  1.2685,  1.4809,  0.1096,  0.6270],
         [ 0.6306,  0.6754, -0.0224, -1.3717, -0.3372],
         [ 1.1837,  0.6354, -0.2030,  0.5417,  0.3509]]])